Add tag tracking
IchHabRecht/git-wrapper pull request #4
Opened 2017-03-01 10:10 UTC by brannow

Allows to gather tag information

2017-03-05 19:00 UTC, IchHabRecht requested changes

2017-03-05 19:00 UTC, IchHabRecht commented on src/GitWrapper/GitRepository.php
> +    const TAG_ORIGIN = 'tags';
As this doesn't belong to the function, I would kindly ask you to remove the unnecessary constant.

2017-03-06 22:29 UTC, IchHabRecht commented
Thanks for this pull request. Nearly perfect now, but a test like "testTagReturnsTags" is missing. Would you mind to add it?

2017-03-07 09:49 UTC, IchHabRecht requested changes

2017-03-07 09:49 UTC, IchHabRecht commented on tests/GitWrapper/GitRepositoryTest.php
> +            array_reverse($localRepository->tag(['l']))
why do you use array_reverse here? you could define $tags in the expected order already and re-use it for your assertion

2017-03-07 09:49 UTC, IchHabRecht commented on tests/GitWrapper/GitRepositoryTest.php
> +        $tagStrings = [
please rename to $tags

2017-03-07 09:58 UTC, brannow commented on tests/GitWrapper/GitRepositoryTest.php
> +            array_reverse($localRepository->tag(['l']))
`git tag -l` reorder the tags itself. 
the reverse was simply to be compensate the missing option in git under 2.0. 
yes, It not really necessary.

2017-03-12 15:10 UTC, merged